name: Authorization Service Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build and Start Firebase Emulator
        run: |
          # Build the Firebase Emulator Image
          docker build -t firebase-emulator ./firebase-emulator
          # Run the Firebase Emulator Container
          docker run -d --name firebase-emulator \
            -p 4000:4000 \
            -p 9099:9099 \
            -e FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} \
            -e FIREBASE_TOKEN=${{ secrets.FIREBASE_TOKEN }} \
            -e FIREBASE_AUTH_EMULATOR_HOST=${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }} \
            firebase-emulator

      - name: Build and Start Authentication Service
        run: |
          # Build the AuthService Image
          docker build -t authservice ./AuthService
          # Run the AuthService Container
          docker run -d --name authservice \
            -p 8000:8000 \
            -e FIREBASE_WEB_API_KEY=${{ secrets.FIREBASE_WEB_API_KEY }} \
            -e FIREBASE_AUTH_EMULATOR_HOST=${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }} \
            -e FIREBASE_SERVICE_ACCOUNT_KEY=${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }} \
            authservice

      - name: Run Unit and Integration Tests on Authentication Service
        run: |
          # Run pytest inside the authservice container
          docker exec authservice pytest
        env:
          FIREBASE_WEB_API_KEY: ${{ secrets.FIREBASE_WEB_API_KEY }}
          FIREBASE_AUTH_EMULATOR_HOST: ${{ secrets.FIREBASE_AUTH_EMULATOR_HOST }}
          FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}

      - name: Stop and Remove Containers
        run: |
          # Stop and clean up the containers
          docker stop firebase-emulator authservice
          docker rm firebase-emulator authservice

      - name: Log In to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Authorization Service Image
        run: |
          # Build and push the authservice image to GitHub Container Registry
          docker build -t ghcr.io/douty/bites/authservice:latest ./AuthService
          docker push ghcr.io/douty/bites/authservice:latest
